react events
james-aguirre/c0323-code-solutions pull request #109
Opened 2023-05-19 21:05 UTC by james-aguirre

<img width="540" alt="Screenshot 2023-05-19 at 2 04 36 PM" src="https://github.com/james-aguirre/c0323-code-solutions/assets/121325991/9689b6b4-33e8-4fda-bac6-eea3ba4bfea7">
<img width="490" alt="Screenshot 2023-05-19 at 2 05 01 PM" src="https://github.com/james-aguirre/c0323-code-solutions/assets/121325991/4686db9f-a635-400c-957c-fe85909befd5">

2023-05-19 21:20 UTC, RobertGardner requested changes
First step fine, next step still to go.

2023-05-19 21:20 UTC, RobertGardner commented on react-events/my-app/src/App.js
> +function App() {
Please put a blank line after the last import statement.

2023-05-19 21:20 UTC, RobertGardner commented on react-events/my-app/src/CustomButton.js
> +  function handleClick() {
This is correct for the first phase of the exercise. Now do the steps near the end that have you move this function into App.

2023-05-21 02:05 UTC, james-aguirre commented
<img width="606" alt="Screenshot 2023-05-20 at 7 02 24 PM" src="https://github.com/james-aguirre/c0323-code-solutions/assets/121325991/299499b2-a69d-4877-9e8e-54fc73886e64">

2023-05-22 15:56 UTC, RobertGardner approved these changes

2023-05-22 15:56 UTC, RobertGardner commented on react-events/my-app/src/CustomButton.js
> +  message,
You don't use this anymore so you should remove it.

2023-05-22 23:50 UTC, merged