Css two column layout - James Aguirre
james-aguirre/c0323-code-solutions pull request #37
Opened 2023-04-02 19:46 UTC by james-aguirre

<img width="1231" alt="Screenshot 2023-04-02 at 12 38 57 PM" src="https://user-images.githubusercontent.com/121325991/229375474-b7e2aab8-c3a8-4d61-905c-9f958ac491e4.png">

2023-04-04 15:45 UTC, shawnkost requested changes
You seemed to have accidentally added `css-two-column-layout` to this as well. Please delete this folder like you did on the previous exercises, and then recommit / push.

2023-04-04 16:03 UTC, shawnkost requested changes
Some changes requested James!

2023-04-04 16:03 UTC, shawnkost commented on css-two-column-layout/index.html
> +      <div class="column-half"></div>
You don't have any content inside this `column-half` `div`, you should have all of your content for this column inside here.

2023-04-04 16:03 UTC, shawnkost commented on css-two-column-layout/index.html
> +      <div class="column-half"></div>
You don't have any content inside this `column-half` `div`, you should have all of your content for this column inside here.

2023-04-04 16:03 UTC, shawnkost commented on css-two-column-layout/index.html
> +      <div class="column-half"></div>
You don't have any content inside this `column-half` `div`, you should have all of your content for this column inside here.

2023-04-04 16:03 UTC, shawnkost commented on css-two-column-layout/index.html
> +      <div class="column-half"></div>
You don't have any content inside this `column-half` `div`, you should have all of your content for this column inside here.

2023-04-08 22:49 UTC, james-aguirre commented
<img width="1341" alt="Screenshot 2023-04-08 at 3 48 33 PM" src="https://user-images.githubusercontent.com/121325991/230745718-c9683dce-b617-416a-b096-9d4b24e36a7d.png">

2023-04-10 17:38 UTC, shawnkost approved these changes
👍🏻

2023-04-10 23:08 UTC, merged