Css four column layout
james-aguirre/c0323-code-solutions pull request #46
Opened 2023-04-05 20:31 UTC by james-aguirre

![Screenshot 2023-04-05 at 1 30 36 PM](https://user-images.githubusercontent.com/121325991/230203798-cb681e6d-cae3-467c-8041-169b715a2e5b.png)

2023-04-10 17:28 UTC, shawnkost requested changes
Some changes here James!

2023-04-10 17:28 UTC, shawnkost commented on css-four-column-layout/styles.css
> +  padding-left: 130px;
You shouldn't need to be setting such high `px` values. If you need to do something this large, then you are probably doing something "hacky" to get this to work.

2023-04-10 17:28 UTC, shawnkost commented on css-four-column-layout/styles.css
> +}
If these are supposed to be columns of 4, why are you setting the `width` to 100%? Shouldn't this be `flex-basis: 25%`?

2023-04-10 17:28 UTC, shawnkost commented on css-four-column-layout/styles.css
> +}
Same note as above ^

2023-04-17 22:36 UTC, james-aguirre commented
![Screenshot 2023-04-17 at 3 36 21 PM](https://user-images.githubusercontent.com/121325991/232625198-6fafe7cb-5df5-47eb-99b5-44efc6af8970.png)

2023-04-24 17:29 UTC, shawnkost approved these changes
👍🏻

2023-05-07 22:45 UTC, merged